[package]
name = "suggestion"
version = "0.1.0"
edition = "2024"

[dependencies]
dhoni = "0.1.0"
upodesh = "0.2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.wasm-bindgen]
version = "0.2"
features = ["serde-serialize"]
